spring.application.name=tests


spring.datasource.url=jdbc:postgresql://localhost:5432/spring_test
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.web.error.include-message=always

jwt.secret=8bc0c7f5b66792cfd6f0ef00a650678efc897ac5efe576c5e6c1bacf7fb35b58